# Generated by Django 3.2.25 on 2024-08-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_taskassignments_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
