# Generated by Django 3.2.25 on 2024-08-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_project_task_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
