# Generated by Django 3.2.25 on 2024-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_taskassignments_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
