# Generated by Django 3.2.25 on 2024-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned',
        ),
        migrations.AddField(
            model_name='resource',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
